### ISSUE TITLE
Some way to get secure URL for picture-URL

### ISSUE THREAD

**Issue by fluffy** [auth0/passport-linkedin-oauth2#13]
LinkedIn support getting a secure or insecure picture URL with a call like

GET http://api.linkedin.com/v1/people/~:(picture-url;secure=true)
GET http://api.linkedin.com/v1/people/~:(picture-url)

But right now this module only seems to support the insure version. It would be nice if there were a way to tell it to get the secure version or the pircture-uri. 

Thanks.

**Comment by jfromaniello** [comment]
Sorry for the long delay, you can do this as follows:
~~~javascript
var strategy = new LinkedinStrategy({
  //...
  profileFields: ["picture-url;secure=true", x, y, z]
});
~~~
