### ISSUE TITLE
Does passport-linkedin-oauth2 check the validity of the "state"

### ISSUE THREAD

**Issue by ordinaryworld** [auth0/passport-linkedin-oauth2#17]
I looked through the code but I am not sure if passport or the passport-linkedin-oauth2 checks the validity of the "state" when it is returned in the callback to prevent CSRF attacks?

**Comment by jfromaniello** [comment]
Now yes, you can do this:

https://github.com/auth0/passport-linkedin-oauth2#auto-handle-state-param
