### ISSUE TITLE
Atate parameter

### ISSUE THREAD

**Issue by jenshk** [auth0/passport-linkedin-oauth2#20]
Whenever the below code is run options.state is always undefined. If params['state']  is just set to a random string, the authentication work

 // LinkedIn requires state parameter. It will return an error if not set.
  if (options.state) {
    params['state'] = options.state;
  }

In setting up the strategy the state option is set.  Any ideas if this is a bug or it's my mistake ?

**Comment by jfromaniello** [comment]
Check the readme of this module, it says:

```javascript
app.get('/auth/linkedin',
  passport.authenticate('linkedin', { state: 'SOME STATE'  }),
  function(req, res){
    // The request will be redirected to LinkedIn for authentication, so this
    // function will not be called.
  });
```
