### ISSUE TITLE
req.isAuthenticated() always false

### ISSUE THREAD

**Issue by msdark** [auth0/passport-linkedin-oauth2#21]
i'm trying to implement the linkedin authentication using your module.
  
    passport.serializeUser (user, done) ->
	  done(null, user.id)

    passport.deserializeUser (obj, done) ->
	  done(null,obj)

    passport.use new LinkedInStrategy
		clientID:'XXXXXXXXX'
		clientSecret:'XXXXXXXX'
		callbackURL:'http://localhost:8090/api/v1/auth/linkedin/callback'
		scope:['r_fullprofile','r_emailaddress','r_contactinfo','w_messages']
		passReqToCallback: true
	,(req,accessToken,refreshToken,profile,done) ->
		email = profile._json.emailAddress
		User.findOne emailAddress:email, (err,user) ->
			if err then return done(err)
			if not err and user != null
				return done(null,user)
			user = new User
				emailAddress:email
				firstName:profile._json.firstName
				lastName:profile._json.lastName
				headline:profile._json.headline
				pictureUrl:profile._json.pictureUrl
				provider:'linkedin'
				provider_id:profile.id
			user.save (err,usr) ->
				if err then return done(err)
			process.nextTick () ->
				return done(null,user)

    ##Some routes
    app.get '/api/v1/auth/linkedin',passport.authenticate('linkedin',{state:'SOME-STATE'}), ->

    app.get '/api/v1/auth/linkedin/callback',passport.authenticate('linkedin',{failureRedirect:'/'}), (req,res) ->
       res.redirect('/')
    
    #This always is false
    app.get '/api/v1/loggedin', (req,res) ->
        if req.isAuthenticated() 
            res.send req.user 
        else
            res.send 0

The last route always return 0 because req.isAuthenticated() always return false even if i visit the authenticate url ( /api/v1/auth/linkedin ) ...

**Comment by jfromaniello** [comment]
Yes, this is related to session or cookies not with this module.

Make sure you see the cookie being set, and try to decode it manually.

**Comment by raphaelyancey** [comment]
I've had the same problem. It was because I didn't initialized the session module in the app.

`npm install --save express-session`

 And, in `app.js`
```
var session = require('express-session');
// ...
app.use(session());
```

Hope it will help some of you!
