### ISSUE TITLE
failed to obtain access token or Unknown authentication scheme

### ISSUE THREAD

**Issue by msdark** [auth0/passport-linkedin-oauth2#26]
My code (coffeescript)

    strategy = new LinkedInStrategy
        clientID:'clientID'
        clientSecret:'clientSecret'
        callbackURL:"#{app.get('config').host}/api/v1/auth/linkedin/callback"
        scope:['r_emailaddress','r_contactinfo']
      ,(accessToken,refreshToken,profile,done) ->
          #Code to get the user

      oldRequest = strategy._oauth2._request;
      strategy._oauth2._request = (method, url, headers, post_body, access_token, callback) ->
          body = qs.parse(post_body);
          if not body.grant_type or body.grant_type != 'authorization_code'
              return oldRequest.apply(@, arguments)
          request.post
              url: url,
              headers: headers,
              qs: body,
             , (err, r, body) ->
                 callback(err, body, r)

     passport.user strategy

With that I get

    failed to fetch user profile (status: 401 data: {
       "errorCode": 0,
       "message": "Unknown authentication scheme",
       "requestId": "IBKWILF41R",
       "status": 401,
       "timestamp": 1420663599509
    })
     at /Users/msdark/Development/jobfoundry/node_modules/passport-linkedin-oauth2/lib/oauth2.js:29:28

If I remove the strategy._oauth2._request code, the request takes forever and finally get this error

    failed to obtain access token (status: 400 data: {"error_description":"missing required parameters, includes an invalid parameter value, parameter more than once. : Unable to retrieve access token : appId or redirect uri does not match authorization code or authorization code expired","error":"invalid_request"})
    at /Users/msdark/Development/jobfoundry/node_modules/passport-linkedin-oauth2/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:125:38

**Comment by cpenarrieta** [comment]
@msdark  i am getting same error. were you able to solve it?

**Comment by siacomuzzi** [comment]
LinkedIn uses a custom name for the access_token parameter (`&oauth2_access_token={YOUR_ACCESS_TOKEN}`).

Try calling the following method before make the request:

```
strategy._oauth2.setAccessTokenName("oauth2_access_token");
```

**Comment by zgordan-vv** [comment]
It works, thank you, Signor SiacoMuzzi!

**Comment by heironimus** [comment]
To follow up with @siacomuzzi 's comment, you can either set the token in the header, or as a query parameter with the name `oauth2_access_token`
