### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by fiznool** [auth0/passport-linkedin-oauth2#33]
Is this module still being maintained? If not, would you be up for some help?

**Comment by tjwebb** [comment]
:/

**Comment by siacomuzzi** [comment]
Yes, we are here :)

Sorry for the delay in responding.

**Comment by tjwebb** [comment]
Nothing's been merged for almost a year. Not very convincing.

**Comment by fiznool** [comment]
Thanks! Looking forward to the other PRs being merged in and a new npm release soon :-)
