### ISSUE TITLE
Get big user avatar

### ISSUE THREAD

**Issue by YanaSavchenko** [auth0/passport-linkedin-oauth2#35]
Is there some way to get big user's avatar using passportjs?
Now it's only 80x80

**Comment by siacomuzzi** [comment]
Try with the following scope: `r_basicprofile -> picture-urls::(original)`

**Comment by YanaSavchenko** [comment]
I've tried everything. 'The scope is unknown'
picture-urls::(original)
picture-url::(original)
r_basicprofile picture-urls::(original)
r_basicprofile picture-url::(original)
r_basicprofile -> picture-urls::(original)
r_basicprofile -> picture-url::(original)

 passport.use(new LinkedInStrategy({
        clientID          : configAuth.linkedinAuth.clientID,
        clientSecret      : configAuth.linkedinAuth.clientSecret,
        callbackURL       : configAuth.linkedinAuth.callbackURL,
        scope             : [ 'r_basicprofile', 'r_emailaddress', 'picture-urls::(original)' ],
        passReqToCallback : true
    }

**Comment by siacomuzzi** [comment]
Please try with `passport-linkedin-oauth2@1.4.0`

```
var user_picture = user._json.pictureUrls.values[0];
```

**Comment by YanaSavchenko** [comment]
Thank you! Sorry about old version. 
And thanks for making authorization easier!

Have a nice day.

**Comment by siacomuzzi** [comment]
it wasn't an old version, I created `v1.4.0` a couple of minutes ago :)
