### ISSUE TITLE
Add all pictures in profile photos

### ISSUE THREAD

**Issue by JSteunou** [auth0/passport-linkedin-oauth2#41]
linkedin also return `pictureUrls` which is like 

``` json
  "pictureUrls": {
    "_total": 1,
    "values": ["https://media.licdn.com/mpr/mprx/0_PQwK..."]
  }
```

could be used in profile `photos` attribute.

**Comment by oieesah** [comment]
*** I will remove this comment.

 I am only getting "pictureUrl" in response and not "pictureUrls" or "picture-urls::(original)".
Any idea how i can get the full image?

**Comment by siacomuzzi** [comment]
Hi @oieesah, please check the following:

1. [Linkedin Developer Portal](http://developer.linkedin.com/) -> `My Apps` -> `{YOUR_APP_NAME}` -> `Default Application Permissions`: Enable `r_basicprofile`
2. `LinkedInStrategy` settings: make sure to include `scope: [ 'r_basicprofile' ]`

Then `pictureUrls` should be available in `profile._json` object.

**Comment by oieesah** [comment]
@siacomuzzi I have verified both of these points.

The response i am getting is this:

{ emailAddress: 'haseebkhilji@gmail.com',
     firstName: 'Haseeb',
     headline: 'Student',
     id: 'pTTFC8Wm7-',
     industry: 'Computer Software',
     lastName: 'Ahmad',
     location: { country: [Object], name: 'Pakistan' },
     pictureUrl: 'https://media.licdn.com/mpr/mprx/0_ORAOgKuovqDjSz0_AEbKVN9oPqYjHN0-cRWOZkion5-yHXY-U05xnC3oK5GjH5-0UDd11kCEs_fpwrBY-eqGvkfQ0_fgwrV0BeqjY5VwqCVAT63_RJCPOAqsx9zSGrSaOIK-JURSaxs',
     publicProfileUrl: 'https://www.linkedin.com/in/haseeb-ahmad-52b11455' }


You can see, not pictureUrls.

**Comment by siacomuzzi** [comment]
Check `profile._json` object (https://github.com/auth0/passport-linkedin-oauth2/blob/master/lib/oauth2.js#L48-L50)

**Comment by oieesah** [comment]
Yes i did.

Following is the complete "profile" object (including ._json):

{ provider: 'linkedin',
  id: 'pTTFC8Wm7-',
  displayName: 'Haseeb Ahmad',
  name: { familyName: 'Ahmad', givenName: 'Haseeb' },
  emails: [ { value: 'haseebkhilji@gmail.com' } ],
  _raw: '{\n  "emailAddress": "haseebkhilji@gmail.com",\n  "firstName": "Haseeb",\n  "headline": "Student",\n  "id": "pTTFC8Wm7-",\n  "industry": "Computer Software",\n  "lastName": "Ahmad",\n  "location": {\n    "country": {"code": "pk"},\n    "name": "Pakistan"\n  },\n  "pictureUrl": "https://media.licdn.com/mpr/mprx/0_ORAOgKuovqDjSz0_AEbKVN9oPqYjHN0-cRWOZkion5-yHXY-U05xnC3oK5GjH5-0UDd11kCEs_fpwrBY-eqGvkfQ0_fgwrV0BeqjY5VwqCVAT63_RJCPOAqsx9zSGrSaOIK-JURSaxs",\n  "publicProfileUrl": "https://www.linkedin.com/in/haseeb-ahmad-52b11455"\n}',
  _json:
   { emailAddress: 'haseebkhilji@gmail.com',
     firstName: 'Haseeb',
     headline: 'Student',
     id: 'pTTFC8Wm7-',
     industry: 'Computer Software',
     lastName: 'Ahmad',
     location: { country: [Object], name: 'Pakistan' },
     pictureUrl: 'https://media.licdn.com/mpr/mprx/0_ORAOgKuovqDjSz0_AEbKVN9oPqYjHN0-cRWOZkion5-yHXY-U05xnC3oK5GjH5-0UDd11kCEs_fpwrBY-eqGvkfQ0_fgwrV0BeqjY5VwqCVAT63_RJCPOAqsx9zSGrSaOIK-JURSaxs',
     publicProfileUrl: 'https://www.linkedin.com/in/haseeb-ahmad-52b11455' } }

**Comment by siacomuzzi** [comment]
you are using `passport-linkedin-oauth2@1.4.x`, right?

please put a `console.log(this.profileUrl)` here: https://github.com/auth0/passport-linkedin-oauth2/blob/master/lib/oauth2.js#L19 and show us the output.

**Comment by oieesah** [comment]
I have copied this response from console. Yes i have download this module today. To be more specific, i am using "passport-linkedin-oauth2": "~1.4.1"

**Comment by siacomuzzi** [comment]
please put a `console.log(this.profileUrl)` here: https://github.com/auth0/passport-linkedin-oauth2/blob/master/lib/oauth2.js#L19 and show us the output.

**Comment by oieesah** [comment]
@siacomuzzi Here it is:

https://api.linkedin.com/v1/people/~:(email-address,id,first-name,last-name,picture-url,picture-urls::(original),formatted-name,maiden-name,phonetic-first-name,phonetic-last-name,formatted-phonetic-name,headline,location:(name,country:(code)),industry,distance,relation-to-viewer:(distance,connections),current-share,num-connections,num-connections-capped,summary,specialties,positions,site-standard-profile-request,api-standard-profile-request:(headers,url),public-profile-url)

**Comment by siacomuzzi** [comment]
looks good.

could you please try with another linkedin user?

**Comment by oieesah** [comment]
@siacomuzzi Good point, Sure.

**Comment by oieesah** [comment]
@siacomuzzi Same result.

**Comment by siacomuzzi** [comment]
These are my strategy options:

```
{ scope: [ 'r_basicprofile' ],
  clientID: '...',
  clientSecret: '...',
  callbackURL: 'https://mywebapp.com/login/callback' }
```

my `this.profileUrl` value:

```
https://api.linkedin.com/v1/people/~:(id,first-name,last-name,picture-url,picture-urls::(original),formatted-name,maiden-name,phonetic-first-name,phonetic-last-name,formatted-phonetic-name,headline,location:(name,country:(code)),industry,distance,relation-to-viewer:(distance,connections),current-share,num-connections,num-connections-capped,summary,specialties,positions,site-standard-profile-request,api-standard-profile-request:(headers,url),public-profile-url)
```

And my `profile._json` object:

```
{
  // ...
  pictureUrl: 'https://media.licdn.com/mpr/mprx/...',
  pictureUrls: { _total: 1, values: [Object] },
}
```

Maybe you can try with a new LinkedIn app?

**Comment by oieesah** [comment]
Alright. I will let you know.

**Comment by oieesah** [comment]
Created new LinkedIn app. The response is same as before. No "pictureUrls" exist.

**Comment by JSteunou** [comment]
Is linkedin expose the same API or same version to everyone, every country
?

**Comment by oieesah** [comment]
@JSteunou Sorry, i didn't get your question.

@siacomuzzi Which version of "Passport" you are using?

**Comment by JSteunou** [comment]
@oieesah I mean, it's weird that some of us get `pictureUrls` and you do not despite your different tests. So I though, maybe it's not the same API version. Or maybe LinkedIn do not send the same result depending the country we set in our profile due to local laws...

**Comment by oieesah** [comment]
@JSteunou That's not possible, linkedIn is a global service so does it's API.

**Comment by siacomuzzi** [comment]
> Which version of "Passport" you are using?

`passport-linkedin-oauth2@1.4.1`

I just created a new LinkedIn app and its works as expected:

![image](https://cloud.githubusercontent.com/assets/178506/17570031/221c25f2-5f21-11e6-91e0-c4e5bd4f29a5.png)

**Comment by oieesah** [comment]
On a side note, can we get profile photo without linkedin watermark on them?

**Comment by siacomuzzi** [comment]
Check [LinkedIn API documentation](https://developer.linkedin.com/docs), but I think you can't do that.

**Comment by oieesah** [comment]
Does full photo from "pictureUrls::(Original)" also contains watermark?

**Comment by siacomuzzi** [comment]
yes, bottom-right corner

**Comment by oieesah** [comment]
@siacomuzzi 

"picutreUrls.values[0]" value is same as "pictureUrl"?

I am talking in reference to the response you shared.

**Comment by siacomuzzi** [comment]
No. `pictureUrls.values[0]` is the original unformatted profile picture. From doc:

* pictureUrl (`picture-url`): A URL to the member's formatted profile picture, if one has been provided.
* picturesUrl (`picture-urls::(original)`): A URL to the member's original unformatted profile picture.  This image is usually larger than the picture-url value above.

**Comment by oieesah** [comment]
@siacomuzzi 
I have tried almost all options there is. 

1. Created new apps.
2. Added all possible callback URLs.
3. Tried with new Users.

But not getting "picture-urls".

**Comment by siacomuzzi** [comment]
Try submitting your issue in [LinkedIn Dev Support](https://developer.linkedin.com/support)

**Comment by oieesah** [comment]
@siacomuzzi How i can validate whether my app is making oauth2 call or not?

**Comment by siacomuzzi** [comment]
Sorry, I don't understand the question. If you are using `passport-linkedin-oauth2`, then you are making oauth2 calls (https://www.linkedin.com/uas/oauth2/authorization and https://www.linkedin.com/uas/oauth2/accessToken)

**Comment by oieesah** [comment]
I am using passport-linkedin-oauth2. My response is same as the one i was getting with passport-linkedIn. So i thought may be my web-app isn't really making OAuth2 calls at all.

**Comment by oieesah** [comment]
@siacomuzzi 
My app is authorising with linkedIn using https://www.linkedin.com/uas/oauth/authorize?oauth_token=

Why not oauth2? May be this the reason i was not getting the pictureUrls.

**Comment by siacomuzzi** [comment]
Please debug your app, if you are using `passport-linkedin-oauth2`, initial request should be `https://www.linkedin.com/uas/oauth2/authorization ` (see https://github.com/auth0/passport-linkedin-oauth2/blob/master/lib/oauth2.js#L8)

**Comment by oieesah** [comment]
Thanks @siacomuzzi

**Comment by siacomuzzi** [comment]
@oieesah can I close this issue?

**Comment by oieesah** [comment]
@siacomuzzi Yes sure!

**Comment by lavarajallu** [comment]
@siacomuzzi when displaying the pictureUrl in Image tag in react native it is not displaying in android but showing in ios
How to solve this?
