### ISSUE TITLE
linkedin does not have a method of identification configured.

### ISSUE THREAD

**Issue by adonisv79** [auth0/passport-linkedin-oauth2#44]
Hi, I am trying to connect my app to my linkedin app using this. however I get the following errors

"linkedin does not have a method of identification configured."

```
options = {
    scope: ['r_emailaddress']
};

passport.authenticate(application_id, options, function (err, user, response) {
     if (err) console.log(err.message); //this happens
}
```

I am not sure if this is because I did not define state but testing it out this occurs...

```
options = {
    state: true,
    scope: ['r_emailaddress']
};

passport.authenticate(application_id, options, function (err, user, response) {
     if (err) console.log(err.message); //this will not happen as err is null
     if (user) { //do something }  //this will also not happen as user will contain false
     if (response && response.message) {
           console.log(response.message); //prints "Unable to verify authorization request state."
     }
}
```

is this a bug? not sure coz I did follow the instructions already. thanks

**Comment by siacomuzzi** [comment]
Hi,

2nd approach should works. Try debugging the SessionStore:

1) Before redirect to linkedin, request state is persisted here: https://github.com/jaredhanson/passport-oauth2/blob/master/lib/state/session.js#L44
2) When linkedin comes back to your app, request state is taken from https://github.com/jaredhanson/passport-oauth2/blob/master/lib/state/session.js#L67

**Comment by adonisv79** [comment]
Good day Sir,

I tested it and it seems that this code was never triggered

```
SessionStore.prototype.store = function(req, callback) {
  if (!req.session) { return callback(new Error('OAuth 2.0 authentication requires session support when using state. Did you forget to use express-session middleware?')); }

  var key = this._key;
  var state = uid(24);
  if (!req.session[key]) { req.session[key] = {}; }
  req.session[key].state = state;
  callback(null, state);
};
```

however the 2nd code you mentioned was which triggers that response.

```
SessionStore.prototype.verify = function(req, providedState, callback) {
  if (!req.session) { return callback(new Error('OAuth 2.0 authentication requires session support when using state. Did you forget to use express-session middleware?')); }

  var key = this._key;
  if (!req.session[key]) {
   **return callback(null, false, { message: 'Unable to verify authorization request state.' });**
  }

  var state = req.session[key].state;
  if (!state) {
   return callback(null, false, { message: 'Unable to verify authorization request state.' });
  }

  delete req.session[key].state;
  if (Object.keys(req.session[key]).length === 0) {
   delete req.session[key];
  }

  if (state !== providedState) {
   return callback(null, false, { message: 'Invalid authorization request state.' });
  }

  return callback(null, true);
};
```

**Comment by siacomuzzi** [comment]
Make sure to set "state: true" in both endpoints (login and callback)

**Comment by adonisv79** [comment]
Hi sir, Not sure what you meant but this is what is bein called in the network:
https://www.linkedin.com/uas/oauth2/authorization?state=true&response_type=code&redirect_uri=xxxxxxxxxx

http://my.callback/path?code=xxxxxxxxxxxxxxx&state=true

**Comment by adonisv79** [comment]
oh nvm, it seems that we were not supposed to use state = true on our design. the first message was another module's error. anyway thanks for the support. we will try to resolve this on our end.
