### ISSUE TITLE
Linkedin authorizationURL and tokenURL changed.

### ISSUE THREAD

**Issue by ljnet** [auth0/passport-linkedin-oauth2#45]
need to add 2 parameters:

passport.use(new LinkedInStrategy({
  clientID: clientID,
  clientSecret: clientSecret,
  callbackURL: callbackURL,
  authorizationURL: 'https://www.linkedin.com/oauth/v2/authorization',
  tokenURL: 'https://www.linkedin.com/oauth/v2/accessToken',
  scope: ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'],
  state: true
  },

**Comment by JSteunou** [comment]
@siacomuzzi any chance to update the default urls in this lib?

**Comment by siacomuzzi** [comment]
done. please use `passport-linkedin-oauth2@1.5.0`

**Comment by JSteunou** [comment]
Thank you.
