### ISSUE TITLE
InternalOAuthError: failed to fetch user profile

### ISSUE THREAD

**Issue by xeroxoid** [auth0/passport-linkedin-oauth2#55]
Hi,

As noted here: https://community.auth0.com/answers/13949/view due to some changes/glitches (not clear yet) in the linkedIn API users are not longer able to log in using this library. It seems that the auth0 team has a workaround for the hosted solution, but could we (people using this library) also get a hotfix/patch to work around this issue?

**Comment by adrogon** [comment]
@xeroxoid Please see #24

**Comment by xeroxoid** [comment]
Great thanks! The title of issue #24 was a bit vague thus did not come up after a quick search.
