### ISSUE TITLE
Clarification on maintainance status of this repository

### ISSUE THREAD

**Issue by cdimitroulas** [auth0/passport-linkedin-oauth2#79]
It seems that this repository is no longer being maintained as there have been no changes in the last 7 months, despite the need for them.

There are several Pull Requests open for important changes (some which are breaking production environments!) which are not being looked at.

If this is no longer being maintained, that's fine - just put a disclaimer on the readme so that at least it's clear for everyone.

Thank you! :)

**Comment by dalelotts** [comment]
I think it's safe to say this is no longer maintained.

**Comment by goatandsheep** [comment]
@jfromaniello
