### ISSUE TITLE
Changing scope causes an error.

### ISSUE THREAD

**Issue by ggsjyoon** [auth0/passport-linkedin-oauth2#8]
Hello. I'm learning Node.js (Express 3) and trying to make a simple web app using LinkedIn REST API. I've been testing passport-linkedin-oauth2 module lately and found a potential bug. I'm not sure it's from the module or from LinkedIn side.

The problem is that changing scope causes an error.
(The project is at https://github.com/ggsjyoon/Job_Search_App)

Initially I did authentication with everything, and it worked fine.
var API_SCOPE = [
 'r_basicprofile',
 'r_fullprofile',
 'r_emailaddress',
 'r_network',
 'r_contactinfo',
 'rw_nus',
 'rw_groups',
 'w_messages'];

Then, I tried authentication again with less scopes, and it stopped working.
var API_SCOPE = [ 'r_basicprofile',  'r_fullprofile'];
or
var API_SCOPE = [ 'r_basicprofile']

The error message is...
failed to fetch user profile (status: 401 data: {
  "errorCode": 0,
  "message": "Unable to verify access token",
  "requestId": "FJI5PKEE1H",
  "status": 401,
  "timestamp": 1392598443466
})
    at D:\WebstormProjects\Job_Search_App\node_modules\passport-linkedin-oauth2\lib\oauth2.js:29:28
    at passBackControl (D:\WebstormProjects\Job_Search_App\node_modules\passport-linkedin-oauth2\node_modules\passport-oauth\node_modules\oauth\lib\oauth2.js:109:9)
    at IncomingMessage.<anonymous> (D:\WebstormProjects\Job_Search_App\node_modules\passport-linkedin-oauth2\node_modules\passport-oauth\node_modules\oauth\lib\oauth2.js:128:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

I also tried changing Default Scope section on the Application Detail page of LinkedIn, but it did not work either.

<br>EDIT 1 :</br> 
When I'm logged into LinkedIn on my desktop, it works.
For example, 
1) log-in LinkedIn.com on a desktop
2) Run the Express project
3) go to localhost:3000/auth/linkedin
4) The Authorization dialog does not popup
5) Able to retrieve my profile in JSON.

However, if I run the app when I'm logged off from LinkedIn.com, it doesn't work.
1) log-off LinkedIn.com on a desktop
2) Run the Express project
3) go to localhost:3000/auth/linkedin
4) the Authorization dialog pops up and hit the Allow Access button.
5) Above error message appears.

I have a feeling that I'm doing something wrong. I'm not sure what it is.

EDIT 2 : 
I made a new LinkedIn account to test more.
When I use the new LinkedIn account, it works in the two cases from EDIT 1.

**Comment by AlmogBaku** [comment]
+1 this also hapepned to me

**Comment by siacomuzzi** [comment]
LinkedIn requires state parameter. It will return an error if not set. See https://github.com/auth0/passport-linkedin-oauth2#auto-handle-state-param
